### ISSUE TITLE
Bad program

### ISSUE THREAD

**Issue by Brokop** [barborik/paker#1]
PAK'd PAGEFILE.sys to make windows faster, windows now no boot properly >:( 
please fix now.

**Comment by barborik** [comment]
have you tried modifying your ROM with a magnetized needle and some elbow grease to resolve the issue?

**Comment by Brokop** [comment]
Okay okay man. Your program PAKs things, good. Not a big deal. Now how do I unpak my windows?

**Comment by barborik** [comment]
decompilation feature added, see this [commit](https://github.com/barborik/paker/commit/1fe0492fabe3f6ea212cd2f7e4bcef9063b5588c)
